### PR TITLE
Added patient recent trainings to dashboard

### PR DESCRIPTION
**Pull request by Jelmerovereem**

### CODE REVIEW

**Comment by StanBankras** [comment]
I think the training in the dropdown when clicking on a patient should be sorted the other way around (latest should be at the top rather than the bottom)

**Comment by StanBankras** [comment]
Also discoverability of this dropdown is bad. A user can't know that this is even there, there should maybe be some kind of 'carrot-down' icon to show it can open.

**Comment by StanBankras** [comment]
Feature itself works good! Nice job 👍

**Comment by Jelmerovereem** [comment]
> I think the training in the dropdown when clicking on a patient should be sorted the other way around (latest should be at the top rather than the bottom)

Ah I totally forgot about that. Thanks

**Comment by Jelmerovereem** [comment]
> Also discoverability of this dropdown is bad. A user can't know that this is even there, there should maybe be some kind of 'carrot-down' icon to show it can open.

True, I'll add a carrot-down or maybe a plus icon that turns into a minus icon. We'll see what's best.

**Review by StanBankras — APPROVED** [review]

**Pull request merged**
