### PR TITLE
Update HTML semantically

### PR DESCRIPTION
**Pull request by StanBankras**

### CODE REVIEW

**Review by Jelmerovereem — APPROVED** [review]

**Comment by Jelmerovereem** [comment]
https://github.com/ofahchouch-gh/gyro-project/blob/e8c2ad34a2ea7ff915e953df42593467ad4c9872/www/src/views/Dashboard.vue#L25-L32
 @StanBankras  Should anything in here also be converted to a section? Or just leave it like this.

**Comment by StanBankras** [comment]
> https://github.com/ofahchouch-gh/gyro-project/blob/e8c2ad34a2ea7ff915e953df42593467ad4c9872/www/src/views/Dashboard.vue#L25-L32
> 
> 
> @StanBankras Should anything in here also be converted to a section? Or just leave it like this.

Hmm yea, I think each training individually is not a  section, but where we now have class="sessions", this could be a section probably.

**Comment by Jelmerovereem** [comment]
> > https://github.com/ofahchouch-gh/gyro-project/blob/e8c2ad34a2ea7ff915e953df42593467ad4c9872/www/src/views/Dashboard.vue#L25-L32
> > 
> > @StanBankras Should anything in here also be converted to a section? Or just leave it like this.
> 
> Hmm yea, I think each training individually is not a section, but where we now have class="sessions", this could be a section probably.

Check, did it ✅

**Comment by StanBankras** [comment]
> > > https://github.com/ofahchouch-gh/gyro-project/blob/e8c2ad34a2ea7ff915e953df42593467ad4c9872/www/src/views/Dashboard.vue#L25-L32
> > > 
> > > @StanBankras Should anything in here also be converted to a section? Or just leave it like this.
> > 
> > 
> > Hmm yea, I think each training individually is not a section, but where we now have class="sessions", this could be a section probably.
> 
> Check, did it ✅

Thanks!!

**Pull request merged**
