### PR TITLE
Feature/add patient

### PR DESCRIPTION
**Pull request by ofahchouch-gh**
Created add patient and patient overview

### CODE REVIEW

**Comment by StanBankras** [comment]
'Here' link doesnt lead me to the form to add a new patient.

**Comment by StanBankras** [comment]
I can't create a new patient:
new

**Comment by ofahchouch-gh** [comment]
> 'Here' link doesnt lead me to the form to add a new patient.

Thanks, fixed the route path name.

**Comment by ofahchouch-gh** [comment]
> I can't create a new patient:
> new

Ah, i forgot to make an error toastr message for when someone tries to add a new patient without being logged in. 

It would even be better to add a route guard, so that the page will not be rendered for those who are not logged in. But i have to figure out how that works in Vue, i used to do that with Angular for such things. If there is time over i can add a route guard. For now i will make an error toastr message that tells the person he/she can't add a patient without being logged in.

**Pull request merged**
