### PR TITLE
Feature/results colors

### PR DESCRIPTION
**Pull request by StanBankras**

### CODE REVIEW

**Review by Jelmerovereem — CHANGES_REQUESTED** [review]
Why use a dependency for formatting the time? I understand that it's easy and readable, but it's an extra dependency while you can just format it with vanilla JS.

**Comment by StanBankras** [comment]
> Why use a dependency for formatting the time? I understand that it's easy and readable, but it's an extra dependency while you can just format it with vanilla JS.

I will remove this dependency and use the functions made for it in the dashboard page. You're right 👍

**Comment by Jelmerovereem** [comment]
> > Why use a dependency for formatting the time? I understand that it's easy and readable, but it's an extra dependency while you can just format it with vanilla JS.
> 
> I will remove this dependency and use the functions made for it in the dashboard page. You're right 👍

You're the best xd

**Review by Jelmerovereem — APPROVED** [review]
Great!

**Pull request merged**
